

dubbo:
  scan:
    base-packages: com.uu.service
  protocol:
    name: dubbo
  registry:
    address: nacos://localhost:8848
    group: dubbo
  metadata-report:
    address: nacos://localhost:8848
    group: dubbo
  consumer:
    check: false
spring:
  application:
    name: dubbo-test
